// The New Tiptris : Recompiled — application entry point.
// Modeled on the standard N64: Recompiled harness (BanjoRecomp-style).
#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <string>
#include <thread>
#include <vector>
#ifdef __linux__
#include <unistd.h>
#include <execinfo.h>
#include <csignal>
#endif

#include "SDL.h"

#include "librecomp/game.hpp"
#include "librecomp/rsp.hpp"
#include "ultramodern/ultramodern.hpp"
#include "ultramodern/renderer_context.hpp"
#include "ultramodern/config.hpp"
#include "ultramodern/input.hpp"
#include "ultramodern/events.hpp"
#include "ultramodern/error_handling.hpp"
#include "ultramodern/threads.hpp"

#include "recompui/recompui.h"
#include "recompui/renderer.h"
#include "recompui/program_config.h"
#include "recompui/config.h"
#include "recompinput/recompinput.h"
#include "recompinput/input_state.h"
#include "recompinput/input_events.h"
#include "recompinput/players.h"
#include "recompinput/profiles.h"

#include "ui_theme.h"   // recompui theme API (internal header; see executable.cmake)

#include <nfd.h>

// ---- Generated by N64Recomp (in RecompiledFuncs) --------------------------
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);
extern gpr get_entrypoint_address();
// Defined in register_overlays.cpp
namespace tnt { void register_overlays(); }

// ---------------------------------------------------------------------------
// Globals the RecompFrontend (recompui) expects the app to provide.
// ---------------------------------------------------------------------------
SDL_Window* window = nullptr;                          // referenced by recompui/ui_state.cpp
std::vector<recomp::GameEntry> supported_games;        // referenced by recompui/ui_launcher.cpp

// ---------------------------------------------------------------------------
// Graphics callbacks
// ---------------------------------------------------------------------------
static ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
    SDL_InitSubSystem(SDL_INIT_VIDEO);
    return nullptr;
}

static ultramodern::renderer::WindowHandle create_window(ultramodern::gfx_callbacks_t::gfx_data_t) {
    window = SDL_CreateWindow(
        "The New Tiptris : Recompiled",
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        1280, 960,
        SDL_WINDOW_VULKAN | SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI);
    return window;
}

static void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t) {
    // Single event pump: recompinput::handle_events() polls SDL, updates game
    // input, and queues events to recompui (which processes them in its render
    // hook). Doing our own SDL_PollEvent/try_deque_event here steals events and
    // breaks menu hover/input.
    recompinput::handle_events();
}

static void vi_callback() {
}

// ---------------------------------------------------------------------------
// Renderer callback — hand RT64 to ultramodern via recompui.
// ---------------------------------------------------------------------------
static std::unique_ptr<ultramodern::renderer::RendererContext>
create_render_context(uint8_t* rdram, ultramodern::renderer::WindowHandle window_handle, bool developer_mode) {
    return recompui::renderer::create_render_context(
        rdram, window_handle,
        ultramodern::renderer::PresentationMode::PresentEarly,
        developer_mode);
}

// ---------------------------------------------------------------------------
// Input callbacks (backed by recompinput)
// ---------------------------------------------------------------------------
static ultramodern::input::connected_device_info_t get_connected_device_info(int controller_num) {
    return { controller_num == 0 ? ultramodern::input::Device::Controller
                                 : ultramodern::input::Device::None,
             ultramodern::input::Pak::None };
}

// ---------------------------------------------------------------------------
// RSP microcode dispatch. Graphics tasks go to the renderer; audio (aspMain)
// would be recompiled here later. Returning nullptr for now (no audio yet).
// ---------------------------------------------------------------------------
// Recompiled TNT audio microcode (rsp/n_aspMain.cpp).
RspExitReason n_aspMain(uint8_t* rdram, uint32_t ucode_addr);

// Safety wrapper: if the microcode hits an audio command whose handler wasn't
// captured by static analysis, report the task as completed rather than letting
// ultramodern treat it as a fatal error and quit the whole game.
static RspExitReason n_aspMain_safe(uint8_t* rdram, uint32_t ucode_addr) {
    RspExitReason reason = n_aspMain(rdram, ucode_addr);
    if (reason != RspExitReason::Broke) {
        return RspExitReason::Broke;
    }
    return reason;
}

static RspUcodeFunc* get_rsp_microcode(const OSTask* task) {
    (void)task; // graphics tasks are routed to the renderer before reaching here;
                // the only other task type this game submits is the audio task.
    return n_aspMain_safe;
}

// ---------------------------------------------------------------------------
// Audio output (SDL). ultramodern hands us interleaved stereo s16 samples that
// the recompiled aspMain microcode produced; we queue them to an SDL device.
// ---------------------------------------------------------------------------
static SDL_AudioDeviceID g_audio_dev = 0;

static void audio_set_frequency(uint32_t freq) {
    if (g_audio_dev != 0) {
        SDL_CloseAudioDevice(g_audio_dev);
        g_audio_dev = 0;
    }
    fprintf(stderr, "[tnt] set_frequency(%u)\n", freq);
    SDL_AudioSpec want{}, have{};
    want.freq = (int)freq;
    want.format = AUDIO_S16SYS;
    want.channels = 2;
    want.samples = 1024;
    want.callback = nullptr; // queue-based
    g_audio_dev = SDL_OpenAudioDevice(nullptr, 0, &want, &have, 0);
    if (g_audio_dev != 0) {
        SDL_PauseAudioDevice(g_audio_dev, 0);
        fprintf(stderr, "[tnt] audio device opened: %d Hz, %d ch\n", have.freq, have.channels);
    } else {
        fprintf(stderr, "[tnt] SDL_OpenAudioDevice failed: %s\n", SDL_GetError());
    }
}

static FILE* g_audio_dump = nullptr;   // raw s16 stereo dump for diagnostics
static uint64_t g_qs_calls = 0, g_qs_samples = 0;

static void audio_queue_samples(int16_t* samples, size_t count) {
    // Guard against a bad/huge buffer from the audio HLE path.
    if (g_audio_dev != 0 && samples != nullptr && count > 0 && count < (1u << 22)) {
        SDL_QueueAudio(g_audio_dev, samples, (Uint32)(count * sizeof(int16_t)));
        if (getenv("TNT_AUDIO_DUMP")) {
            if (!g_audio_dump) g_audio_dump = fopen("/tmp/tnt_audio.raw", "wb");
            if (g_audio_dump) fwrite(samples, sizeof(int16_t), count, g_audio_dump);
        }
        g_qs_calls++; g_qs_samples += count;
        if ((g_qs_calls % 200) == 0) {
            fprintf(stderr, "[tnt] audio: %llu calls, %llu samples, queued=%u bytes\n",
                (unsigned long long)g_qs_calls, (unsigned long long)g_qs_samples,
                (unsigned)SDL_GetQueuedAudioSize(g_audio_dev));
        }
    }
}

#ifdef __linux__
static void tnt_crash_handler(int sig) {
    void* bt[48];
    int n = backtrace(bt, 48);
    fprintf(stderr, "\n[tnt] CRASH: signal %d — backtrace (%d frames):\n", sig, n);
    backtrace_symbols_fd(bt, n, 2);
    signal(sig, SIG_DFL);
    raise(sig);
}
#endif

static size_t audio_get_frames_remaining() {
    if (g_audio_dev == 0) {
        return 0;
    }
    // Two s16 channels per frame.
    return SDL_GetQueuedAudioSize(g_audio_dev) / (2 * sizeof(int16_t));
}

// ---------------------------------------------------------------------------
static std::string get_game_thread_name(const OSThread* t) {
    return "tnt_game_thread";
}

#define TRACE(msg) do { fprintf(stderr, "[tnt] " msg "\n"); fflush(stderr); } while (0)

int main(int argc, char** argv) {
    (void)argc; (void)argv;

    TRACE("start");
    // Make the app runnable from any directory: assets are resolved relative to
    // the cwd (recompui's get_program_path() returns ""), so chdir to the exe dir.
#ifdef __linux__
    {
        char exe_path[4096];
        ssize_t n = readlink("/proc/self/exe", exe_path, sizeof(exe_path) - 1);
        if (n > 0) {
            exe_path[n] = '\0';
            std::error_code ec;
            std::filesystem::current_path(std::filesystem::path(exe_path).parent_path(), ec);
        }
    }
#endif
    setvbuf(stdout, nullptr, _IONBF, 0); // unbuffered so microcode diagnostics flush
#ifdef __linux__
    signal(SIGSEGV, tnt_crash_handler);
    signal(SIGABRT, tnt_crash_handler);
#endif
    recompui::programconfig::set_program_name("The New Tiptris : Recompiled");
    SDL_SetHint(SDL_HINT_JOYSTICK_THREAD, "1");
    // WSLg / most desktops route audio through PulseAudio; ALSA's "default"
    // device frequently fails there, so prefer PulseAudio/PipeWire before ALSA.
    if (SDL_getenv("SDL_AUDIODRIVER") == nullptr) {
        SDL_setenv("SDL_AUDIODRIVER", "pulseaudio", 1);
    }
    SDL_Init(SDL_INIT_AUDIO);
    NFD_Init();
    fprintf(stderr, "[tnt] audio driver: %s\n", SDL_GetCurrentAudioDriver() ? SDL_GetCurrentAudioDriver() : "(none)");
    TRACE("sdl+nfd init");

    // Config/save location.
    std::filesystem::path config_dir =
        std::filesystem::path(SDL_GetPrefPath("N64Recomp", "TheNewTiptris"));
    recomp::register_config_path(config_dir);
    TRACE("config path registered");

    // Register the recompiled sections and the game.
    tnt::register_overlays();
    TRACE("overlays registered");

    recomp::GameEntry game{};
    game.rom_hash = 0xEDDC4D3AEF798119ULL; // XXH3_64 of the NTSC-U ROM
    game.internal_name = "TETRIS";
    game.display_name = "The New Tiptris";
    game.game_id = u8"tnt.n64.us";
    game.mod_game_id = "tnt";
    game.save_type = recomp::SaveType::AllowAll;
    game.is_enabled = true;
    game.has_compressed_code = false;
    game.entrypoint_address = get_entrypoint_address();
    game.entrypoint = recomp_entrypoint;
    supported_games.push_back(game);
    recomp::register_game(supported_games.back());
    TRACE("game registered");

    recompinput::profiles::initialize_input_bindings();
    // Single-player: assign the keyboard as player 1 so the game sees a controller
    // and receives input (otherwise no device is bound and it reports NO CONTROLLER).
    recompinput::players::set_single_player_mode(true);
    recompinput::playerassignment::add_keyboard_player();
    recompinput::playerassignment::commit_player_assignment();
    TRACE("input bindings init + keyboard assigned as P1");

    // Register the primary UI font (resolved as <program_dir>/assets/<name> by recompui).
    // recompui itself loads assets/recomp.rcss and the fallback fonts during UI init.
    recompui::register_primary_font("fonts/primary.ttf", "primary");
    TRACE("primary font registered");

    // Controls menu: show this game's actions instead of raw N64 button names,
    // and hide the N64 inputs the game doesn't use (bindings still work — this
    // only affects which rows the Controls menu lists).
    {
        using GI = recompinput::GameInput;
        recompinput::set_game_input_name(GI::A,          "Rotate CW");
        recompinput::set_game_input_name(GI::B,          "Rotate CCW");
        recompinput::set_game_input_name(GI::Z,          "Hold");
        recompinput::set_game_input_name(GI::START,      "Start / Pause");
        recompinput::set_game_input_name(GI::DPAD_LEFT,  "Left");
        recompinput::set_game_input_name(GI::DPAD_RIGHT, "Right");
        recompinput::set_game_input_name(GI::DPAD_UP,    "Up");
        recompinput::set_game_input_name(GI::DPAD_DOWN,  "Down");
        recompinput::set_game_input_description(GI::A, "Rotate the piece clockwise (confirm in menus)");
        recompinput::set_game_input_description(GI::B, "Rotate the piece counter-clockwise (back in menus)");
        recompinput::set_game_input_description(GI::Z, "Hold / swap the current piece");
        for (GI gi : { GI::L, GI::R, GI::C_UP, GI::C_DOWN, GI::C_LEFT, GI::C_RIGHT,
                       GI::X_AXIS_NEG, GI::X_AXIS_POS, GI::Y_AXIS_POS, GI::Y_AXIS_NEG }) {
            recompinput::set_game_input_disabled(gi, true);
        }
        recompinput::set_game_input_name(GI::ACCEPT_MENU, "Accept");
        recompinput::set_game_input_name(GI::BACK_MENU,   "Back");
    }

    // Menu theme: a cohesive dark palette (deep charcoal + teal accent) for the
    // launcher and config menus. recompui styles menus inline from these theme
    // colors, so set them before the UI is created.
    {
        using recompui::Color;
        namespace th = recompui::theme;
        th::set_theme_color(th::color::Background1, Color{13, 17, 23, 255});   // deep charcoal
        th::set_theme_color(th::color::Primary,     Color{45, 212, 191, 255}); // teal accent
        th::set_theme_color(th::color::Secondary,   Color{251, 146, 60, 255}); // warm amber
        th::set_theme_color(th::color::Elevated,    Color{45, 212, 191, 38});  // hover/focus fill
        th::set_theme_color(th::color::Text,        Color{230, 237, 243, 255});
        th::set_theme_color(th::color::TextDim,     Color{139, 148, 158, 255});
        th::set_theme_color(th::color::TextActive,  Color{255, 255, 255, 255});
        th::set_border_radius_md(14.0f);
    }

    // Config tabs (general/graphics/sound/controls), then load from disk.
    recompui::config::create_general_tab(recompui::config::GeneralTabOptions{});
    recompui::config::create_graphics_tab();
    recompui::config::create_sound_tab();
    recompui::config::create_controls_tab();
    recompui::config::finalize();
    TRACE("config finalized");

    recomp::rsp::callbacks_t rsp_callbacks{ .get_rsp_microcode = get_rsp_microcode };
    ultramodern::renderer::callbacks_t renderer_callbacks{ .create_render_context = create_render_context };
    ultramodern::audio_callbacks_t audio_callbacks{
        .queue_samples = audio_queue_samples,
        .get_frames_remaining = audio_get_frames_remaining,
        .set_frequency = audio_set_frequency,
    };
    ultramodern::input::callbacks_t input_callbacks{
        .poll_input = recompinput::poll_inputs,
        .get_input = recompinput::profiles::get_n64_input,
        .set_rumble = recompinput::set_rumble,
        .get_connected_device_info = get_connected_device_info,
    };
    ultramodern::gfx_callbacks_t gfx_callbacks{
        .create_gfx = create_gfx,
        .create_window = create_window,
        .update_gfx = update_gfx,
    };
    ultramodern::events::callbacks_t events_callbacks{ .vi_callback = vi_callback };
    ultramodern::error_handling::callbacks_t error_callbacks{ .message_box = recompui::message_box };
    ultramodern::threads::callbacks_t threads_callbacks{ .get_game_thread_name = get_game_thread_name };

    // Test/dev auto-boot: if TNT_ROM points at a ROM, validate+store it, then
    // trigger the game the same way the launcher's "Start Game" button does, but
    // from the launcher update callback so it runs on the UI thread.
    if (const char* rom_env = std::getenv("TNT_ROM")) {
        std::u8string gid = game.game_id;
        recomp::RomValidationError err = recomp::select_rom(std::filesystem::path(rom_env), gid);
        TRACE("auto-boot: select_rom done");
        if (err == recomp::RomValidationError::Good) {
            recompui::register_launcher_update_callback([gid](recompui::LauncherMenu*) {
                static int frame = 0;
                static bool started = false;
                if (!started && ++frame > 120) {
                    started = true;
                    fprintf(stderr, "[tnt] auto-boot: start_game (UI thread)\n"); fflush(stderr);
                    recomp::start_game(gid, {});
                    recompui::hide_all_contexts();
                }
            });
        } else {
            fprintf(stderr, "[tnt] auto-boot: ROM validation failed (%d)\n", (int)err); fflush(stderr);
        }
    }

    TRACE("calling recomp::start");
    recomp::start(
        recomp::Version{1, 0, 0},
        {},
        rsp_callbacks,
        renderer_callbacks,
        audio_callbacks,
        input_callbacks,
        gfx_callbacks,
        events_callbacks,
        error_callbacks,
        threads_callbacks
    );

    return 0;
}
